version: '2'

services:

    ssvapi:
        container_name: ssvapi
        build:
            context: ../services.schools
            dockerfile: ./services.schools/dev.dockerfile
        ports:
            - "8080:8080"
        environment:
            - NODE_ENV=development
        networks:
            - ssv-network

    ssvui:
        container_name: ssvui
        build:
            context: ../ui
            dockerfile: ./ui/dev.dockerfile
        ports:
            - "80:80"
        environment:
            - NODE_ENV=development
        networks:
            - ssv-network

#    mongodb:
#        image: mongodb
#        networks:
#            - ssv-network

networks:
    ssv-network:
        driver: bridge